const DataPoint = require('data-point');
const assert = require('assert');

const dataPoint = DataPoint.create();

dataPoint.addEntities({
    'model:getArray': {
        // points to a NON Array value
        value: '$a.b',
        outputType: 'array',
        error: (error) => {
            // prints out the error
            // message generated by
            // isArray type check
            console.log('error.message:', error.message)

            console.log('Value is invalid, resolving to empty array')

            // passing a value will stop
            // the propagation of the error
            return []
        }
    }
})

const input = {
    a: {
        b: 'foo'
    }
}

dataPoint
    .resolve('model:getArray', input)
    .then((output) => {
        console.log('output:', output);
        assert.deepEqual(output, [])
    })